from pydantic import BaseModel

from ..models import BootstrapPayload, ArchitectureBlock, BrandInfo, FeaturedClaim, StackLibrary


class KnowledgeCitation(BaseModel):
    refId: str


class KnowledgeSource(BaseModel):
    id: str
    title: str
    url: str
    domain: str
    snippet: str
    sourceBucket: str
    journalType: str
    evidenceTier: str
    stance: str
    topics: list[str]
    citations: list[KnowledgeCitation]


BOOTSTRAP = BootstrapPayload(
    brand=BrandInfo(
        name="GramWIN",
        tagline="Health and Wellness at your fingertips",
        accent=["#b9ec83", "#7fd5e6", "#164a93", "#cc3b3f"],
    ),
    featuredClaims=[
        FeaturedClaim(id="c1", claim="Magnesium glycinate will cure insomnia", whyItIsInteresting="Strong language and a common supplement promise."),
        FeaturedClaim(id="c2", claim="Gut health supplements can fix eczema", whyItIsInteresting="Cross-domain claim that often mixes mechanism and outcome."),
        FeaturedClaim(id="c3", claim="Apple cider vinegar burns fat fast", whyItIsInteresting="Popular wellness claim with lots of low-quality content."),
    ],
    architecture=[
        ArchitectureBlock(id="a1", title="Claim analyzer", summary="Reads the claim semantically as a whole, scores certainty, and generates meaning-preserving evidence queries."),
        ArchitectureBlock(id="a2", title="Source scout", summary="Searches broadly with SerpAPI and deeply with Tavily before ranking candidate evidence sources."),
        ArchitectureBlock(id="a3", title="Source validator", summary="Drops dead or inaccessible links and keeps only readable source text for downstream review."),
        ArchitectureBlock(id="a4", title="Quote verifier", summary="Verifies each displayed quote directly against the source text before it can appear in the UI."),
        ArchitectureBlock(id="a5", title="Decision engine", summary="Combines source quality, evidence depth, dual-model sentiment agreement, and claim-evidence fit into the final verdict."),
    ],
    suggestedLibraries=[
        StackLibrary(id="l1", name="FastAPI", category="API", whyItHelps="Clean async-friendly backend for job orchestration and polling.", adoptionNote="Already used here."),
        StackLibrary(id="l2", name="SQLite", category="Persistence", whyItHelps="Simple durable storage for investigations, stage runs, and progress logs.", adoptionNote="Used now; swap to Postgres later if needed."),
        StackLibrary(id="l3", name="Tavily or SerpAPI", category="Search", whyItHelps="Plug-in live web search when you want real discovery instead of seeded fallback data.", adoptionNote="Wire in via API keys."),
        StackLibrary(id="l4", name="OpenAlex / Crossref / Semantic Scholar", category="Scholarly metadata", whyItHelps="Useful for journal metadata, citation graphs, and academic source enrichment.", adoptionNote="Best next upgrade for evidence quality."),
        StackLibrary(id="l5", name="trafilatura", category="Extraction", whyItHelps="Readable text extraction from articles and study pages before agent analysis.", adoptionNote="Recommended future dependency."),
        StackLibrary(id="l6", name="OpenAI structured outputs", category="LLM reasoning", whyItHelps="Optional upgrade for better query generation and narrative synthesis.", adoptionNote="This backend is designed to support it."),
    ],
    storageNote="Investigations, agent runs, and progress events are persisted in SQLite so history survives app restarts.",
)


KNOWLEDGE_SOURCES: list[KnowledgeSource] = [
    KnowledgeSource(
        id="src-cochrane-magnesium-sleep",
        title="Dietary supplements for sleep problems in adults",
        url="https://www.cochrane.org/example/magnesium-sleep-review",
        domain="cochrane.org",
        snippet="Review-level evidence suggests mixed support for supplements affecting sleep quality, with limited certainty for magnesium-specific insomnia claims.",
        sourceBucket="tier_3_authority",
        journalType="systematic review",
        evidenceTier="review",
        stance="mixed",
        topics=["magnesium", "sleep", "insomnia", "supplement"],
        citations=[KnowledgeCitation(refId="src-nih-sleep-supplements"), KnowledgeCitation(refId="src-rct-magnesium-sleep")],
    ),
    KnowledgeSource(
        id="src-rct-magnesium-sleep",
        title="Randomized trial of magnesium supplementation in adults with poor sleep",
        url="https://pubmed.ncbi.nlm.nih.gov/example-magnesium-rct",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="A small randomized trial found modest improvement in some sleep measures, but not evidence that magnesium cures insomnia.",
        sourceBucket="tier_3_authority",
        journalType="randomized controlled trial",
        evidenceTier="rct",
        stance="mixed",
        topics=["magnesium", "sleep", "insomnia"],
        citations=[],
    ),
    KnowledgeSource(
        id="src-nih-sleep-supplements",
        title="Sleep disorders and dietary supplements",
        url="https://www.nccih.nih.gov/health/sleep-disorders-and-dietary-supplements",
        domain="nccih.nih.gov",
        snippet="Supplements may have limited evidence for sleep support, but strong curative claims are not supported.",
        sourceBucket="tier_3_authority",
        journalType="government guidance",
        evidenceTier="review",
        stance="mixed",
        topics=["magnesium", "sleep", "insomnia", "supplement"],
        citations=[KnowledgeCitation(refId="src-rct-magnesium-sleep")],
    ),
    KnowledgeSource(
        id="src-blog-magnesium-cure",
        title="Why magnesium will cure insomnia forever",
        url="https://wellnessbliss.blog/magnesium-cure-insomnia",
        domain="wellnessbliss.blog",
        snippet="A promotional blog uses absolute language and anecdotal stories to claim magnesium fully cures insomnia.",
        sourceBucket="tier_1_blog",
        journalType="blog post",
        evidenceTier="blog",
        stance="supportive",
        topics=["magnesium", "sleep", "insomnia"],
        citations=[KnowledgeCitation(refId="missing-broken-link")],
    ),
    KnowledgeSource(
        id="src-review-gut-eczema",
        title="Gut microbiome and atopic dermatitis: a narrative review",
        url="https://pmc.ncbi.nlm.nih.gov/example-gut-eczema-review",
        domain="pmc.ncbi.nlm.nih.gov",
        snippet="The gut-skin axis is biologically plausible, but current evidence is insufficient to claim gut health interventions reliably fix eczema.",
        sourceBucket="tier_3_authority",
        journalType="review article",
        evidenceTier="review",
        stance="mixed",
        topics=["gut health", "eczema", "microbiome", "atopic dermatitis", "probiotics"],
        citations=[KnowledgeCitation(refId="src-rct-probiotic-eczema"), KnowledgeCitation(refId="src-observational-gut-skin")],
    ),
    KnowledgeSource(
        id="src-rct-probiotic-eczema",
        title="Randomized trial of probiotics in atopic dermatitis",
        url="https://pubmed.ncbi.nlm.nih.gov/example-probiotic-eczema-rct",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="Trial results showed inconsistent improvement, with effect sizes varying by population and strain.",
        sourceBucket="tier_3_authority",
        journalType="randomized controlled trial",
        evidenceTier="rct",
        stance="mixed",
        topics=["gut health", "eczema", "probiotics"],
        citations=[],
    ),
    KnowledgeSource(
        id="src-observational-gut-skin",
        title="Observational associations between microbiome diversity and eczema severity",
        url="https://jamanetwork.com/example-gut-skin-observational",
        domain="jamanetwork.com",
        snippet="Association data suggests microbiome changes may correlate with eczema severity, but causation is not established.",
        sourceBucket="tier_2_scholarly",
        journalType="observational cohort",
        evidenceTier="observational",
        stance="mixed",
        topics=["gut health", "eczema", "microbiome"],
        citations=[],
    ),
    KnowledgeSource(
        id="src-blog-gut-eczema",
        title="Heal your gut and eczema disappears",
        url="https://glowinsidout.blog/gut-fixes-eczema",
        domain="glowinsidout.blog",
        snippet="Anecdotal wellness article claiming gut repair protocols eliminate eczema for most people.",
        sourceBucket="tier_1_blog",
        journalType="blog post",
        evidenceTier="blog",
        stance="supportive",
        topics=["gut health", "eczema"],
        citations=[KnowledgeCitation(refId="src-review-gut-eczema"), KnowledgeCitation(refId="missing-blog-citation")],
    ),
    KnowledgeSource(
        id="src-nih-acv-weight",
        title="Weight loss supplements and apple cider vinegar claims",
        url="https://ods.od.nih.gov/example-acv-weight",
        domain="ods.od.nih.gov",
        snippet="Evidence for apple cider vinegar and substantial fat loss remains limited, with small studies and modest effects at best.",
        sourceBucket="tier_3_authority",
        journalType="government evidence summary",
        evidenceTier="review",
        stance="contradictory",
        topics=["apple cider vinegar", "fat loss", "weight loss"],
        citations=[KnowledgeCitation(refId="src-rct-acv-weight")],
    ),
    KnowledgeSource(
        id="src-rct-acv-weight",
        title="Randomized trial of vinegar ingestion and weight outcomes",
        url="https://pubmed.ncbi.nlm.nih.gov/example-acv-rct",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="Small trial showed minor differences in weight-related outcomes, not rapid or dramatic fat loss.",
        sourceBucket="tier_3_authority",
        journalType="randomized controlled trial",
        evidenceTier="rct",
        stance="mixed",
        topics=["apple cider vinegar", "weight loss"],
        citations=[],
    ),
    KnowledgeSource(
        id="src-blog-acv-fatloss",
        title="Apple cider vinegar burns fat fast",
        url="https://trimfastblog.example/acv-burns-fat-fast",
        domain="trimfastblog.example",
        snippet="Blog article makes aggressive promises about rapid fat burning without citing strong evidence.",
        sourceBucket="tier_1_blog",
        journalType="blog post",
        evidenceTier="blog",
        stance="supportive",
        topics=["apple cider vinegar", "fat loss", "weight loss"],
        citations=[KnowledgeCitation(refId="src-rct-acv-weight"), KnowledgeCitation(refId="missing-weight-link")],
    ),
]


GENERIC_AUTHORITY_SOURCES: list[KnowledgeSource] = [
    KnowledgeSource(
        id="generic-who-evidence",
        title="Evidence-informed health decision-making overview",
        url="https://www.who.int/example/evidence-informed-decision-making",
        domain="who.int",
        snippet="International guidance emphasizes caution with absolute health claims and prioritizes systematic evidence over anecdotes.",
        sourceBucket="tier_3_authority",
        journalType="international guidance",
        evidenceTier="review",
        stance="mixed",
        topics=["general health claim", "evidence", "credibility"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-pubmed-evidence",
        title="How to interpret clinical evidence and health claims",
        url="https://pubmed.ncbi.nlm.nih.gov/example-evidence-interpretation",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="Clinical evidence should be judged by study quality, reproducibility, and whether source conclusions match the underlying data.",
        sourceBucket="tier_3_authority",
        journalType="review article",
        evidenceTier="review",
        stance="mixed",
        topics=["general health claim", "study quality", "evidence"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-aad-eczema-guidance",
        title="Atopic dermatitis treatment guidance overview",
        url="https://www.aad.org/example/eczema-guidance",
        domain="aad.org",
        snippet="Dermatology guidance supports layered eczema care and does not frame gut-directed therapies as a reliable stand-alone fix.",
        sourceBucket="tier_2_scholarly",
        journalType="clinical guidance",
        evidenceTier="review",
        stance="contradictory",
        topics=["eczema", "atopic dermatitis", "treatment guidance", "gut health"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-nice-eczema-guidance",
        title="Evidence-based eczema management recommendations",
        url="https://www.nice.org.uk/example/eczema-guidance",
        domain="nice.org.uk",
        snippet="Guideline recommendations prioritize established eczema management strategies and treat microbiome-targeted approaches as uncertain or adjunctive.",
        sourceBucket="tier_3_authority",
        journalType="guideline",
        evidenceTier="review",
        stance="contradictory",
        topics=["eczema", "guideline", "treatment", "microbiome"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-probiotic-systematic-review",
        title="Systematic review of probiotics for atopic dermatitis outcomes",
        url="https://pubmed.ncbi.nlm.nih.gov/example-probiotic-systematic-review",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="Meta-analytic findings suggest some probiotic strategies may help subsets of patients, but the overall signal remains inconsistent.",
        sourceBucket="tier_3_authority",
        journalType="systematic review",
        evidenceTier="review",
        stance="mixed",
        topics=["probiotics", "eczema", "atopic dermatitis", "systematic review"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-microbiome-review",
        title="Gut microbiome modulation and inflammatory skin disease",
        url="https://www.nature.com/example-microbiome-skin-review",
        domain="nature.com",
        snippet="Mechanistic reviews describe plausible gut-skin pathways, but translation into clinically reliable eczema improvement remains incomplete.",
        sourceBucket="tier_2_scholarly",
        journalType="review article",
        evidenceTier="review",
        stance="mixed",
        topics=["gut microbiome", "eczema", "skin disease", "mechanism"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-cochrane-probiotics",
        title="Probiotics for eczema: evidence summary",
        url="https://www.cochrane.org/example/probiotics-eczema-summary",
        domain="cochrane.org",
        snippet="Review-level evidence does not support simple cure-style language and points to mixed clinical benefit across studies.",
        sourceBucket="tier_3_authority",
        journalType="systematic review",
        evidenceTier="review",
        stance="contradictory",
        topics=["eczema", "probiotics", "review", "evidence"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-sleep-guideline",
        title="Clinical guidance on insomnia management",
        url="https://www.aasm.org/example-insomnia-guideline",
        domain="aasm.org",
        snippet="Clinical insomnia guidance emphasizes behavioral and evidence-based treatment strategies rather than supplement cure claims.",
        sourceBucket="tier_2_scholarly",
        journalType="guideline",
        evidenceTier="review",
        stance="contradictory",
        topics=["insomnia", "sleep", "guideline", "magnesium"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-magnesium-review",
        title="Magnesium supplementation and sleep quality evidence review",
        url="https://pubmed.ncbi.nlm.nih.gov/example-magnesium-sleep-review",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="Evidence suggests possible modest benefit for some sleep outcomes, but findings remain heterogeneous and not curative.",
        sourceBucket="tier_3_authority",
        journalType="review article",
        evidenceTier="review",
        stance="mixed",
        topics=["magnesium", "sleep", "insomnia", "supplement"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-obesity-guideline",
        title="Evidence-based obesity management and supplement caution",
        url="https://www.nhlbi.nih.gov/example-weight-guidance",
        domain="nhlbi.nih.gov",
        snippet="Weight-management guidance warns against overstating single-food or supplement effects when the evidence is small or inconsistent.",
        sourceBucket="tier_3_authority",
        journalType="guideline",
        evidenceTier="review",
        stance="contradictory",
        topics=["weight loss", "apple cider vinegar", "obesity", "evidence"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-vinegar-review",
        title="Dietary vinegar and metabolic outcomes review",
        url="https://www.sciencedirect.com/example-vinegar-metabolic-review",
        domain="sciencedirect.com",
        snippet="Research on vinegar suggests small or preliminary metabolic effects, not fast fat-burning outcomes.",
        sourceBucket="tier_2_scholarly",
        journalType="review article",
        evidenceTier="review",
        stance="contradictory",
        topics=["apple cider vinegar", "metabolic", "weight loss", "fat loss"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-causation-review",
        title="Correlation, causation, and overclaiming in health research",
        url="https://www.bmj.com/example-correlation-causation-health",
        domain="bmj.com",
        snippet="Health reporting often overstates observational findings, especially when association data is framed as treatment proof.",
        sourceBucket="tier_2_scholarly",
        journalType="commentary review",
        evidenceTier="review",
        stance="mixed",
        topics=["correlation", "causation", "health claim", "evidence quality"],
        citations=[],
    ),
]
