from pydantic import BaseModel

from ..models import BootstrapPayload, ArchitectureBlock, BrandInfo, FeaturedClaim, StackLibrary


class KnowledgeCitation(BaseModel):
    refId: str


class KnowledgeSource(BaseModel):
    id: str
    title: str
    url: str
    domain: str
    snippet: str
    sourceBucket: str
    journalType: str
    evidenceTier: str
    stance: str
    topics: list[str]
    citations: list[KnowledgeCitation]


BOOTSTRAP = BootstrapPayload(
    brand=BrandInfo(
        name="GramWIN",
        tagline="Health and Wellness at your fingertips",
        accent=["#2c6a5a", "#5e78a6", "#e0c36a", "#b15349"],
    ),
    featuredClaims=[
        FeaturedClaim(id="c1", claim="A short video says magnesium glycinate cures insomnia within a week for most adults.", whyItIsInteresting="It mixes a common supplement topic with very strong cure language."),
        FeaturedClaim(id="c2", claim="A wellness post says gut health supplements can fix eczema flare-ups in adults.", whyItIsInteresting="It turns a plausible mechanism story into a much stronger clinical promise."),
        FeaturedClaim(id="c3", claim="A reel says drinking more water is automatically healthy and better than other beverages.", whyItIsInteresting="It sounds reasonable, but still needs wording checks and real evidence context."),
    ],
    architecture=[
        ArchitectureBlock(id="a1", title="Claim Analyst · Medical Doctor", summary="Reads the claim semantically as a whole, separates intervention from outcome, and checks whether the wording overreaches clinically."),
        ArchitectureBlock(id="a2", title="Research Agent · Scientist", summary="Searches broadly and deeply for studies, reviews, guidelines, and contradiction-seeking evidence paths."),
        ArchitectureBlock(id="a3", title="Validation Agent · Data Engineer", summary="Drops dead or inaccessible links, caches extracted content, and keeps only readable evidence for analysis."),
        ArchitectureBlock(id="a4", title="Stance Agent · Epidemiologist", summary="Interprets whether each source supports, contradicts, or remains uncertain based on evidence quality and wording."),
        ArchitectureBlock(id="a5", title="Consensus Agent · Statistician", summary="Weights evidence by source tier and confidence so the final score reflects stronger evidence more heavily."),
        ArchitectureBlock(id="a6", title="Verifier Agent · Auditor", summary="Cross-checks quotes, contradictions, and model disagreements to reduce hallucinations and overconfident claims."),
        ArchitectureBlock(id="a7", title="Summary Agent · Health Communicator", summary="Turns the technical review into short, user-friendly explanations that stay faithful to the evidence."),
    ],
    suggestedLibraries=[
        StackLibrary(id="l1", name="TanStack Query", category="Caching", whyItHelps="Handles request caching, background refresh, and stale-state recovery cleanly in the app.", adoptionNote="Recommended for the next frontend pass."),
        StackLibrary(id="l2", name="Zustand", category="State", whyItHelps="Keeps UI state compact without overloading component trees.", adoptionNote="Good fit for lightweight global app state."),
        StackLibrary(id="l3", name="NLP Cloud", category="NLP", whyItHelps="Useful for semantic parsing, entity extraction, and text classification as an optional specialist layer.", adoptionNote="Best added behind feature flags and fallbacks."),
        StackLibrary(id="l4", name="react-native-paper", category="UI", whyItHelps="Adds polished, production-grade components without sacrificing a clean mobile feel.", adoptionNote="Strong option for the next UI pass."),
        StackLibrary(id="l5", name="react-native-reanimated", category="Motion", whyItHelps="Supports smooth card transitions, swipes, and bottom-sheet interactions.", adoptionNote="Recommended for premium motion work."),
        StackLibrary(id="l6", name="AsyncStorage", category="Offline cache", whyItHelps="Helps preserve lightweight app state and cached results when connectivity is unstable.", adoptionNote="Good for mobile resilience."),
    ],
    storageNote="Saved investigations and progress updates are stored locally so history survives app restarts.",
)


KNOWLEDGE_SOURCES: list[KnowledgeSource] = [
    KnowledgeSource(
        id="src-cochrane-magnesium-sleep",
        title="Dietary supplements for sleep problems in adults",
        url="https://www.cochrane.org/example/magnesium-sleep-review",
        domain="cochrane.org",
        snippet="Review-level evidence suggests mixed support for supplements affecting sleep quality, with limited certainty for magnesium-specific insomnia claims.",
        sourceBucket="tier_3_authority",
        journalType="systematic review",
        evidenceTier="review",
        stance="mixed",
        topics=["magnesium", "sleep", "insomnia", "supplement"],
        citations=[KnowledgeCitation(refId="src-nih-sleep-supplements"), KnowledgeCitation(refId="src-rct-magnesium-sleep")],
    ),
    KnowledgeSource(
        id="src-rct-magnesium-sleep",
        title="Randomized trial of magnesium supplementation in adults with poor sleep",
        url="https://pubmed.ncbi.nlm.nih.gov/example-magnesium-rct",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="A small randomized trial found modest improvement in some sleep measures, but not evidence that magnesium cures insomnia.",
        sourceBucket="tier_3_authority",
        journalType="randomized controlled trial",
        evidenceTier="rct",
        stance="mixed",
        topics=["magnesium", "sleep", "insomnia"],
        citations=[],
    ),
    KnowledgeSource(
        id="src-nih-sleep-supplements",
        title="Sleep disorders and dietary supplements",
        url="https://www.nccih.nih.gov/health/sleep-disorders-and-dietary-supplements",
        domain="nccih.nih.gov",
        snippet="Supplements may have limited evidence for sleep support, but strong curative claims are not supported.",
        sourceBucket="tier_3_authority",
        journalType="government guidance",
        evidenceTier="review",
        stance="mixed",
        topics=["magnesium", "sleep", "insomnia", "supplement"],
        citations=[KnowledgeCitation(refId="src-rct-magnesium-sleep")],
    ),
    KnowledgeSource(
        id="src-blog-magnesium-cure",
        title="Why magnesium will cure insomnia forever",
        url="https://wellnessbliss.blog/magnesium-cure-insomnia",
        domain="wellnessbliss.blog",
        snippet="A promotional blog uses absolute language and anecdotal stories to claim magnesium fully cures insomnia.",
        sourceBucket="tier_1_blog",
        journalType="blog post",
        evidenceTier="blog",
        stance="supportive",
        topics=["magnesium", "sleep", "insomnia"],
        citations=[KnowledgeCitation(refId="missing-broken-link")],
    ),
    KnowledgeSource(
        id="src-review-water-health",
        title="Water intake and health outcomes: review of human evidence",
        url="https://pubmed.ncbi.nlm.nih.gov/example-water-health-review",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="Water consumption is associated with positive health outcomes, especially when it replaces sugar-sweetened beverages, although overall effects still depend on broader diet and context.",
        sourceBucket="tier_3_authority",
        journalType="review article",
        evidenceTier="review",
        stance="supportive",
        topics=["water", "hydration", "health", "beverages"],
        citations=[KnowledgeCitation(refId="generic-who-hydration-guidance")],
    ),
    KnowledgeSource(
        id="src-review-gut-eczema",
        title="Gut microbiome and atopic dermatitis: a narrative review",
        url="https://pmc.ncbi.nlm.nih.gov/example-gut-eczema-review",
        domain="pmc.ncbi.nlm.nih.gov",
        snippet="The gut-skin axis is biologically plausible, but current evidence is insufficient to claim gut health interventions reliably fix eczema.",
        sourceBucket="tier_3_authority",
        journalType="review article",
        evidenceTier="review",
        stance="mixed",
        topics=["gut health", "eczema", "microbiome", "atopic dermatitis", "probiotics"],
        citations=[KnowledgeCitation(refId="src-rct-probiotic-eczema"), KnowledgeCitation(refId="src-observational-gut-skin")],
    ),
    KnowledgeSource(
        id="src-rct-probiotic-eczema",
        title="Randomized trial of probiotics in atopic dermatitis",
        url="https://pubmed.ncbi.nlm.nih.gov/example-probiotic-eczema-rct",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="Trial results showed inconsistent improvement, with effect sizes varying by population and strain.",
        sourceBucket="tier_3_authority",
        journalType="randomized controlled trial",
        evidenceTier="rct",
        stance="mixed",
        topics=["gut health", "eczema", "probiotics"],
        citations=[],
    ),
    KnowledgeSource(
        id="src-observational-gut-skin",
        title="Observational associations between microbiome diversity and eczema severity",
        url="https://jamanetwork.com/example-gut-skin-observational",
        domain="jamanetwork.com",
        snippet="Association data suggests microbiome changes may correlate with eczema severity, but causation is not established.",
        sourceBucket="tier_2_scholarly",
        journalType="observational cohort",
        evidenceTier="observational",
        stance="mixed",
        topics=["gut health", "eczema", "microbiome"],
        citations=[],
    ),
    KnowledgeSource(
        id="src-blog-gut-eczema",
        title="Heal your gut and eczema disappears",
        url="https://glowinsidout.blog/gut-fixes-eczema",
        domain="glowinsidout.blog",
        snippet="Anecdotal wellness article claiming gut repair protocols eliminate eczema for most people.",
        sourceBucket="tier_1_blog",
        journalType="blog post",
        evidenceTier="blog",
        stance="supportive",
        topics=["gut health", "eczema"],
        citations=[KnowledgeCitation(refId="src-review-gut-eczema"), KnowledgeCitation(refId="missing-blog-citation")],
    ),
    KnowledgeSource(
        id="src-nih-acv-weight",
        title="Weight loss supplements and apple cider vinegar claims",
        url="https://ods.od.nih.gov/example-acv-weight",
        domain="ods.od.nih.gov",
        snippet="Evidence for apple cider vinegar and substantial fat loss remains limited, with small studies and modest effects at best.",
        sourceBucket="tier_3_authority",
        journalType="government evidence summary",
        evidenceTier="review",
        stance="contradictory",
        topics=["apple cider vinegar", "fat loss", "weight loss"],
        citations=[KnowledgeCitation(refId="src-rct-acv-weight")],
    ),
    KnowledgeSource(
        id="src-rct-acv-weight",
        title="Randomized trial of vinegar ingestion and weight outcomes",
        url="https://pubmed.ncbi.nlm.nih.gov/example-acv-rct",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="Small trial showed minor differences in weight-related outcomes, not rapid or dramatic fat loss.",
        sourceBucket="tier_3_authority",
        journalType="randomized controlled trial",
        evidenceTier="rct",
        stance="mixed",
        topics=["apple cider vinegar", "weight loss"],
        citations=[],
    ),
    KnowledgeSource(
        id="src-blog-acv-fatloss",
        title="Apple cider vinegar burns fat fast",
        url="https://trimfastblog.example/acv-burns-fat-fast",
        domain="trimfastblog.example",
        snippet="Blog article makes aggressive promises about rapid fat burning without citing strong evidence.",
        sourceBucket="tier_1_blog",
        journalType="blog post",
        evidenceTier="blog",
        stance="supportive",
        topics=["apple cider vinegar", "fat loss", "weight loss"],
        citations=[KnowledgeCitation(refId="src-rct-acv-weight"), KnowledgeCitation(refId="missing-weight-link")],
    ),
]


GENERIC_AUTHORITY_SOURCES: list[KnowledgeSource] = [
    KnowledgeSource(
        id="generic-who-hydration-guidance",
        title="Healthy hydration and beverage choice guidance",
        url="https://www.who.int/example/healthy-hydration-guidance",
        domain="who.int",
        snippet="Healthy hydration guidance favors drinking water as a healthier default beverage and cautions against replacing it with sugary drink options.",
        sourceBucket="tier_3_authority",
        journalType="international guidance",
        evidenceTier="review",
        stance="supportive",
        topics=["water", "hydration", "healthy beverage", "health"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-who-evidence",
        title="Evidence-informed health decision-making overview",
        url="https://www.who.int/example/evidence-informed-decision-making",
        domain="who.int",
        snippet="International guidance emphasizes caution with absolute health claims and prioritizes systematic evidence over anecdotes.",
        sourceBucket="tier_3_authority",
        journalType="international guidance",
        evidenceTier="review",
        stance="mixed",
        topics=["general health claim", "evidence", "credibility"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-pubmed-evidence",
        title="How to interpret clinical evidence and health claims",
        url="https://pubmed.ncbi.nlm.nih.gov/example-evidence-interpretation",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="Clinical evidence should be judged by study quality, reproducibility, and whether source conclusions match the underlying data.",
        sourceBucket="tier_3_authority",
        journalType="review article",
        evidenceTier="review",
        stance="mixed",
        topics=["general health claim", "study quality", "evidence"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-aad-eczema-guidance",
        title="Atopic dermatitis treatment guidance overview",
        url="https://www.aad.org/example/eczema-guidance",
        domain="aad.org",
        snippet="Dermatology guidance supports layered eczema care and does not frame gut-directed therapies as a reliable stand-alone fix.",
        sourceBucket="tier_2_scholarly",
        journalType="clinical guidance",
        evidenceTier="review",
        stance="contradictory",
        topics=["eczema", "atopic dermatitis", "treatment guidance", "gut health"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-nice-eczema-guidance",
        title="Evidence-based eczema management recommendations",
        url="https://www.nice.org.uk/example/eczema-guidance",
        domain="nice.org.uk",
        snippet="Guideline recommendations prioritize established eczema management strategies and treat microbiome-targeted approaches as uncertain or adjunctive.",
        sourceBucket="tier_3_authority",
        journalType="guideline",
        evidenceTier="review",
        stance="contradictory",
        topics=["eczema", "guideline", "treatment", "microbiome"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-probiotic-systematic-review",
        title="Systematic review of probiotics for atopic dermatitis outcomes",
        url="https://pubmed.ncbi.nlm.nih.gov/example-probiotic-systematic-review",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="Meta-analytic findings suggest some probiotic strategies may help subsets of patients, but the overall signal remains inconsistent.",
        sourceBucket="tier_3_authority",
        journalType="systematic review",
        evidenceTier="review",
        stance="mixed",
        topics=["probiotics", "eczema", "atopic dermatitis", "systematic review"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-microbiome-review",
        title="Gut microbiome modulation and inflammatory skin disease",
        url="https://www.nature.com/example-microbiome-skin-review",
        domain="nature.com",
        snippet="Mechanistic reviews describe plausible gut-skin pathways, but translation into clinically reliable eczema improvement remains incomplete.",
        sourceBucket="tier_2_scholarly",
        journalType="review article",
        evidenceTier="review",
        stance="mixed",
        topics=["gut microbiome", "eczema", "skin disease", "mechanism"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-cochrane-probiotics",
        title="Probiotics for eczema: evidence summary",
        url="https://www.cochrane.org/example/probiotics-eczema-summary",
        domain="cochrane.org",
        snippet="Review-level evidence does not support simple cure-style language and points to mixed clinical benefit across studies.",
        sourceBucket="tier_3_authority",
        journalType="systematic review",
        evidenceTier="review",
        stance="contradictory",
        topics=["eczema", "probiotics", "review", "evidence"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-sleep-guideline",
        title="Clinical guidance on insomnia management",
        url="https://www.aasm.org/example-insomnia-guideline",
        domain="aasm.org",
        snippet="Clinical insomnia guidance emphasizes behavioral and evidence-based treatment strategies rather than supplement cure claims.",
        sourceBucket="tier_2_scholarly",
        journalType="guideline",
        evidenceTier="review",
        stance="contradictory",
        topics=["insomnia", "sleep", "guideline", "magnesium"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-magnesium-review",
        title="Magnesium supplementation and sleep quality evidence review",
        url="https://pubmed.ncbi.nlm.nih.gov/example-magnesium-sleep-review",
        domain="pubmed.ncbi.nlm.nih.gov",
        snippet="Evidence suggests possible modest benefit for some sleep outcomes, but findings remain heterogeneous and not curative.",
        sourceBucket="tier_3_authority",
        journalType="review article",
        evidenceTier="review",
        stance="mixed",
        topics=["magnesium", "sleep", "insomnia", "supplement"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-obesity-guideline",
        title="Evidence-based obesity management and supplement caution",
        url="https://www.nhlbi.nih.gov/example-weight-guidance",
        domain="nhlbi.nih.gov",
        snippet="Weight-management guidance warns against overstating single-food or supplement effects when the evidence is small or inconsistent.",
        sourceBucket="tier_3_authority",
        journalType="guideline",
        evidenceTier="review",
        stance="contradictory",
        topics=["weight loss", "apple cider vinegar", "obesity", "evidence"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-vinegar-review",
        title="Dietary vinegar and metabolic outcomes review",
        url="https://www.sciencedirect.com/example-vinegar-metabolic-review",
        domain="sciencedirect.com",
        snippet="Research on vinegar suggests small or preliminary metabolic effects, not fast fat-burning outcomes.",
        sourceBucket="tier_2_scholarly",
        journalType="review article",
        evidenceTier="review",
        stance="contradictory",
        topics=["apple cider vinegar", "metabolic", "weight loss", "fat loss"],
        citations=[],
    ),
    KnowledgeSource(
        id="generic-causation-review",
        title="Correlation, causation, and overclaiming in health research",
        url="https://www.bmj.com/example-correlation-causation-health",
        domain="bmj.com",
        snippet="Health reporting often overstates observational findings, especially when association data is framed as treatment proof.",
        sourceBucket="tier_2_scholarly",
        journalType="commentary review",
        evidenceTier="review",
        stance="mixed",
        topics=["correlation", "causation", "health claim", "evidence quality"],
        citations=[],
    ),
]
